[build]
<<<<<<< HEAD
  base = "react-job-portal"
  publish = "build"
  command = "npm install && npm run build"
=======
  base = "react-job-portal/frontend"
  command = "npm install && npm run build"
  publish = "react-job-portal/frontend/build"
>>>>>>> e605edb (Fix Netlify build path to frontend directory)
